# -*- coding: utf-8 -*-

# Andy Sayler
# Summer 2014
# Univerity of Colorado

import os

# Set Paths
MOD_PATH = os.path.dirname(os.path.realpath(__file__))
ROOT_PATH = os.path.realpath("{:s}/..".format(MOD_PATH))

# Set Default Vals
DEFAULT_REDIS_HOST = "localhost"
DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_DB = 4
DEFAULT_REDIS_PASSWORD = None
DEFAULT_FILE_PATH = os.path.realpath("{:s}/files".format(ROOT_PATH))
DEFAULT_SCRIPT_PATH = os.path.realpath("{:s}/scripts".format(ROOT_PATH))
DEFAULT_ENV_LOCAL_TMP_PATH = "/tmp/cogs"
DEFAULT_ENV_LOCAL_SANDBOX = "local_sandbox.py"
DEFAULT_TESTER_SCRIPT_USER = "nobody"
DEFAULT_TESTER_SCRIPT_GROUP = "nogroup"
DEFAULT_AUTHMOD_MOODLE_HOST = None
DEFAULT_AUTHMOD_MOODLE_SERVICE = None
DEFAULT_REPMOD_MOODLE_HOST = None
DEFAULT_REPMOD_MOODLE_SERVICE = None
DEFAULT_REPMOD_MOODLE_USERNAME = None
DEFAULT_REPMOD_MOODLE_PASSWORD = None

# Get Env Vars
REDIS_HOST = os.environ.get('COGS_REDIS_HOST', DEFAULT_REDIS_HOST)
REDIS_PORT = int(os.environ.get('COGS_REDIS_PORT', DEFAULT_REDIS_PORT))
REDIS_DB = int(os.environ.get('COGS_REDIS_DB', DEFAULT_REDIS_DB))
REDIS_PASSWORD = os.environ.get('COGS_REDIS_PASSWORD', DEFAULT_REDIS_PASSWORD)
FILE_PATH = os.environ.get('COGS_FILE_PATH', DEFAULT_FILE_PATH)
SCRIPT_PATH = os.environ.get('COGS_SCRIPT_PATH', DEFAULT_SCRIPT_PATH)
ENV_LOCAL_TMP_PATH = os.environ.get('COGS_ENV_LOCAL_TMP_PATH', DEFAULT_ENV_LOCAL_TMP_PATH)
ENV_LOCAL_SANDBOX = os.environ.get('COGS_ENV_LOCAL_SANDBOX', DEFAULT_ENV_LOCAL_SANDBOX)
TESTER_SCRIPT_USER = os.environ.get('COGS_TESTER_SCRIPT_USER', DEFAULT_TESTER_SCRIPT_USER)
TESTER_SCRIPT_GROUP = os.environ.get('COGS_TESTER_SCRIPT_GROUP', DEFAULT_TESTER_SCRIPT_GROUP)
AUTHMOD_MOODLE_HOST = os.environ.get('COGS_AUTHMOD_MOODLE_HOST', DEFAULT_AUTHMOD_MOODLE_HOST)
AUTHMOD_MOODLE_SERVICE = os.environ.get('COGS_AUTHMOD_MOODLE_SERVICE', DEFAULT_AUTHMOD_MOODLE_SERVICE)
REPMOD_MOODLE_HOST = os.environ.get('COGS_REPMOD_MOODLE_HOST', DEFAULT_REPMOD_MOODLE_HOST)
REPMOD_MOODLE_SERVICE = os.environ.get('COGS_REPMOD_MOODLE_SERVICE', DEFAULT_REPMOD_MOODLE_SERVICE)
REPMOD_MOODLE_USERNAME = os.environ.get('COGS_REPMOD_MOODLE_USERNAME', DEFAULT_REPMOD_MOODLE_USERNAME)
REPMOD_MOODLE_PASSWORD = os.environ.get('COGS_REPMOD_MOODLE_PASSWORD', DEFAULT_REPMOD_MOODLE_PASSWORD)
